//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMaxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_Entita
    {
        public CB_Entita()
        {
            this.CB_Elaborazioni = new HashSet<CB_Elaborazioni>();
            this.CB_EntitaCampi = new HashSet<CB_EntitaCampi>();
        }
    
        public int id { get; set; }
        public string Nome { get; set; }
        public string NomeTabellaDestinazione { get; set; }
        public string ProceduraEstrazione { get; set; }
        public string PathCSV { get; set; }
        public string PathCSVscarti { get; set; }
        public bool Attivo { get; set; }
    
        public virtual ICollection<CB_Elaborazioni> CB_Elaborazioni { get; set; }
        public virtual ICollection<CB_EntitaCampi> CB_EntitaCampi { get; set; }
    }
}
