//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMaxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_Esito
    {
        public CB_Esito()
        {
            this.CB_Elaborazioni = new HashSet<CB_Elaborazioni>();
        }
    
        public int id { get; set; }
        public string Descrizione { get; set; }
    
        public virtual ICollection<CB_Elaborazioni> CB_Elaborazioni { get; set; }
    }
}
