//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMaxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_EntitaCampiValoriAmmessi
    {
        public int id { get; set; }
        public int id_EntitaCampi { get; set; }
        public string Valore { get; set; }
        public bool Attivo { get; set; }
    
        public virtual CB_EntitaCampi CB_EntitaCampi { get; set; }
    }
}
