//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMaxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_EntitaCampi
    {
        public CB_EntitaCampi()
        {
            this.CB_EntitaCampiValoriAmmessi = new HashSet<CB_EntitaCampiValoriAmmessi>();
        }
    
        public int id { get; set; }
        public int id_Entita { get; set; }
        public string NomeCampoOrigine { get; set; }
        public string NomeCampoDestinazione { get; set; }
        public string Descrizione { get; set; }
        public bool Obbligatorio { get; set; }
        public int Lunghezza { get; set; }
        public int id_TipoCampo { get; set; }
        public int OrdineEstrazione { get; set; }
        public bool Attivo { get; set; }
    
        public virtual CB_Entita CB_Entita { get; set; }
        public virtual ICollection<CB_EntitaCampiValoriAmmessi> CB_EntitaCampiValoriAmmessi { get; set; }
        public virtual CB_TipoCampo CB_TipoCampo { get; set; }
    }
}
