//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMaxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_Elaborazioni
    {
        public int id { get; set; }
        public int id_Entita { get; set; }
        public int id_Tipologia { get; set; }
        public System.DateTime DataDa { get; set; }
        public System.DateTime DataA { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public System.DateTime DataElaborazione { get; set; }
        public int id_Esito { get; set; }
    
        public virtual CB_Entita CB_Entita { get; set; }
        public virtual CB_TipologiaElaborazione CB_TipologiaElaborazione { get; set; }
        public virtual CB_Esito CB_Esito { get; set; }
    }
}
