//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMaxModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CB_TipoCampo
    {
        public CB_TipoCampo()
        {
            this.CB_EntitaCampi = new HashSet<CB_EntitaCampi>();
        }
    
        public int id { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<CB_EntitaCampi> CB_EntitaCampi { get; set; }
    }
}
