//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMaxModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataMaxDBEntities : DbContext
    {
        public DataMaxDBEntities()
            : base("name=DataMaxDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CB_Elaborazioni> CB_Elaborazioni { get; set; }
        public DbSet<CB_Entita> CB_Entita { get; set; }
        public DbSet<CB_EntitaCampi> CB_EntitaCampi { get; set; }
        public DbSet<CB_EntitaCampiValoriAmmessi> CB_EntitaCampiValoriAmmessi { get; set; }
        public DbSet<CB_Esito> CB_Esito { get; set; }
        public DbSet<CB_TipoCampo> CB_TipoCampo { get; set; }
        public DbSet<CB_TipologiaElaborazione> CB_TipologiaElaborazione { get; set; }
    }
}
