//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StagingGalaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GALA_ESPOSIZIONE
    {
        public string ID_AZIENDA { get; set; }
        public string ID_CLIENTE { get; set; }
        public decimal SALDO { get; set; }
        public decimal EXTRA_SALDO { get; set; }
        public Nullable<int> STATO_LAVORAZIONE { get; set; }
    }
}
