//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StagingGalaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GALA_ANAGRAFICA_CONTRATTI
    {
        public string ID_CONTRATTO { get; set; }
        public string ID_AZIENDA { get; set; }
        public string ID_CLIENTE { get; set; }
        public string STATO { get; set; }
        public Nullable<System.DateTime> DATA_INIZIO { get; set; }
        public Nullable<System.DateTime> DATA_FINE { get; set; }
        public Nullable<System.DateTime> DATA_CESSAZIONE { get; set; }
        public string CONV_APPARTENENZA { get; set; }
        public string ID_BU { get; set; }
        public string DESCR_BU { get; set; }
        public string ID_AREA { get; set; }
        public string DESCR_AREA { get; set; }
        public string ID_AGENTE { get; set; }
        public string DESCR_AGENTE { get; set; }
        public string CENTRO_DI_COSTO { get; set; }
        public string ID_PAG_MOD { get; set; }
        public string DESCR_PAG_MOD { get; set; }
        public string CIG { get; set; }
        public string CUP { get; set; }
        public string ODA { get; set; }
        public string IdTipoContratto { get; set; }
        public string DescrizioneTipoContratto { get; set; }
        public string IDAgenzia { get; set; }
        public string NomeAgenzia { get; set; }
    }
}
