//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StagingGalaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GALA_CONTATTI
    {
        public string ID_contatto { get; set; }
        public string ID_CLIENTE { get; set; }
        public string ID_azienda { get; set; }
        public string NOME { get; set; }
        public string COGNOME { get; set; }
        public string ID_TIPOCONTATTO { get; set; }
        public string TIPOCONTATTO { get; set; }
        public string CODFISC { get; set; }
        public string INDIRIZZO { get; set; }
        public string CAP { get; set; }
        public string COMUNE { get; set; }
        public string PROVINCIA { get; set; }
        public string NAZIONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONO { get; set; }
        public string PEC { get; set; }
        public string CELLULARE { get; set; }
        public string RagioneSociale { get; set; }
        public string PartitaIVa { get; set; }
        public string ID_Tipo_persona { get; set; }
        public string Descrizione_tipo_persona { get; set; }
    }
}
