//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StagingGalaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GALA_ANAGRAFICA_CLIENTI
    {
        public string ID_AZIENDA { get; set; }
        public string ID_CLIENTE { get; set; }
        public string ID_MASTER { get; set; }
        public string ID_TIPO_CLIENTE { get; set; }
        public string DESCR_TIPO_CLIENTE { get; set; }
        public string DESC_STATO_CLIENTE { get; set; }
        public string STATO_LAVORAZIONE { get; set; }
        public string ID_Tipo_persona { get; set; }
        public string Descrizione_tipo_persone { get; set; }
        public string PIVA { get; set; }
        public string CODFISC { get; set; }
        public string RAGIONESOCIALE { get; set; }
        public string INDIRIZZO { get; set; }
        public string CAP { get; set; }
        public string COMUNE { get; set; }
        public string PROVINCIA { get; set; }
        public string NAZIONE { get; set; }
        public string FAX { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONO { get; set; }
        public string PEC { get; set; }
        public string CELLULARE { get; set; }
        public Nullable<int> ID_AGENTE { get; set; }
        public string DESCR_AGENTE { get; set; }
        public Nullable<int> ID_AGENZIA { get; set; }
        public string DESCR_AGENZIA { get; set; }
        public string TRATTENUTA_0_5 { get; set; }
        public string CONVENZIONE { get; set; }
        public string FORMA_GIURIDICA { get; set; }
        public string NOME { get; set; }
        public string COGNOME { get; set; }
        public string Classe_di_rischio { get; set; }
        public string Descrizione_del_rischio { get; set; }
        public string ORIGINE_CLIENTE { get; set; }
    }
}
