//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StagingGalaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GALA_GARANZIE_FACTOR
    {
        public string ID_COUNTRY { get; set; }
        public string ID_AZIENDA { get; set; }
        public string ID_CLIENTE { get; set; }
        public decimal ID_GARANZIA { get; set; }
        public Nullable<decimal> ID_GAR_ENTE { get; set; }
        public string DESCR_GAR_ENTE { get; set; }
        public decimal PLAFOND { get; set; }
        public System.DateTime DATA_INIZIO { get; set; }
        public System.DateTime DATA_FINE { get; set; }
        public string DESC_GAR_TIPO { get; set; }
        public decimal ID_GAR_TIPO { get; set; }
        public string PERSONALE { get; set; }
    }
}
