//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StagingGalaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GALA_POD_PDR
    {
        public string ID_AZIENDA { get; set; }
        public string ID_CLIENTE { get; set; }
        public string ID_CONTRATTO { get; set; }
        public int ID_RIGA_CONTRATTI { get; set; }
        public string CODICE_DISPOSITIVO { get; set; }
        public decimal VOL_QTA { get; set; }
        public string COMMODITY { get; set; }
        public string INDIRIZZO { get; set; }
        public string CAP { get; set; }
        public string COMUNE { get; set; }
        public string PROVINCIA { get; set; }
        public string NAZIONE { get; set; }
        public string RIFERIMENTO { get; set; }
        public string CONVENZIONE { get; set; }
        public string CIG { get; set; }
        public string CUP { get; set; }
        public string ODA { get; set; }
        public string CIG_GARA { get; set; }
        public string COMPONENTE_TARIFFARIA { get; set; }
        public System.DateTime DATA_INIZIO { get; set; }
        public System.DateTime DATA_FINE { get; set; }
        public Nullable<System.DateTime> DATA_CESSAZIONE { get; set; }
        public string ID_PAG_MOD { get; set; }
        public string DESCR_PAG_MOD { get; set; }
    }
}
