//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StagingGalaModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StagingGalaDBEntities : DbContext
    {
        public StagingGalaDBEntities()
            : base("name=StagingGalaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GALA_ANAGRAFICA_CLIENTI> GALA_ANAGRAFICA_CLIENTI { get; set; }
        public DbSet<GALA_ANAGRAFICA_CONTRATTI> GALA_ANAGRAFICA_CONTRATTI { get; set; }
        public DbSet<GALA_ANAGRAFICA_MOVIMENTI> GALA_ANAGRAFICA_MOVIMENTI { get; set; }
        public DbSet<GALA_CONTATTI> GALA_CONTATTI { get; set; }
        public DbSet<GALA_ESPOSIZIONE> GALA_ESPOSIZIONE { get; set; }
        public DbSet<GALA_GARANZIE_FACTOR> GALA_GARANZIE_FACTOR { get; set; }
        public DbSet<GALA_POD_PDR> GALA_POD_PDR { get; set; }
    }
}
