CREATE TABLE [dbo].[ANAGRAFICA_CONTRATTI]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ID_CONTRATTO] VARCHAR(20) NOT NULL, 
    [ID_AZIENDA] VARCHAR(10) NOT NULL, 
    [ID_CLIENTE] VARCHAR(30) NOT NULL, 
    [STATO] VARCHAR(10) NOT NULL, 
    [DATA_INIZIO] DATETIME NOT NULL, 
    [DATA_FINE] DATETIME NOT NULL, 
    [DATA_CESSAZIONE] DATETIME NULL, 
    [CONV_APPARTENENZA] VARCHAR(100) NOT NULL, 
    [ID_BU] VARCHAR(10) NULL, 
    [DESCR_BU] VARCHAR(50) NULL, 
    [ID_AREA] VARCHAR(10) NULL, 
    [DESCR_AREA] VARCHAR(50) NULL, 
    [ID_AGENTE] VARCHAR(10) NULL, 
    [DESCR_AGENTE] VARCHAR(50) NULL, 
    [CENTRO_DI_COSTO] VARCHAR(50) NULL, 
    [ID _PAG_MOD] VARCHAR(10) NOT NULL, 
    [DESCR_ PAG_MOD] VARCHAR(50) NOT NULL, 
    [CIG] VARCHAR(200) NULL, 
    [CUP] VARCHAR(200) NULL, 
    [ODA] VARCHAR(200) NULL
)
