CREATE TABLE [dbo].[GALA_ANAGRAFICA_MOVIMENTI] (
	[ID_RECORD] [int] NOT NULL,
	[ID_AZIENDA] [varchar](10) NOT NULL,
	[ID_CLIENTE] [varchar](30) NOT NULL,
	[N_DOC] [varchar](50) NOT NULL,
	[DATA_DOC] [datetime] NOT NULL,
	[DATA_REG] [datetime] NOT NULL,
	[DATA_ACQ] [datetime] NOT NULL,
	[DATA_UPD] [datetime] NULL,
	[DATA_SCAD] [datetime] NOT NULL,
	[SEGNO] [char](1) NOT NULL,
	[VALUTA] [char](3) NOT NULL,
	[IMPORTO] [numeric](18, 2) NOT NULL,
	[IMPONIBILE] [numeric](16, 6) NULL,
	[ID_CAUSALE] [varchar](10) NOT NULL,
	[DESCR_CAUSALE] [varchar](50) NOT NULL,
	[ID_PAG_MOD] [varchar](10) NULL,
	[DESCR_PAG_MOD] [varchar](50) NULL,
	[ID_PAG_TER] [varchar](10) NULL,
	[DESCR_PAG_TER] [varchar](50) NULL,
	[COMMODITY] [varchar](10) NULL,
	[CODICE_PARTITA] [varchar](50) NULL,
	[FACTOR] [varchar](50) NULL,
	[Tipologia_fattura] [varchar](100) NULL,
	[Desscrizione_tipologia_fattura] [varchar](200) NULL,
	[URL] [varchar](2048) NULL
);

