CREATE TABLE [dbo].[GALA_ESPOSIZIONE](
	[ID_AZIENDA] [varchar](10) NOT NULL,
	[ID_CLIENTE] [varchar](30) NOT NULL,
	[SALDO] [numeric](18, 2) NOT NULL,
	[EXTRA_SALDO] [numeric](18, 2) NULL,
	[STATO_LAVORAZIONE] [int] NOT NULL
) ON [PRIMARY]
