CREATE TABLE [dbo].[GALA_GARANZIE_FACTOR]
(
    [ID_COUNTRY] VARCHAR(10) NOT NULL, 
    [ID_AZIENDA] VARCHAR(10) NOT NULL, 
    [ID_CLIENTE] VARCHAR(30) NOT NULL, 
    [ID_GARANZIA] NUMERIC(10) NOT NULL, 
    [ID_GAR_ENTE] NUMERIC(9) NULL, 
    [DESCR_GAR_ENTE] VARCHAR(100) NULL, 
    [PLAFOND] NUMERIC(18, 2) NOT NULL, 
    [DATA_INIZIO] DATETIME NOT NULL, 
    [DATA_FINE] DATETIME NOT NULL, 
    [DESC_GAR_TIPO] VARCHAR(100) NOT NULL, 
    [ID_GAR_TIPO] NUMERIC(9) NOT NULL, 
    [PERSONALE] CHAR NOT NULL, 
    PRIMARY KEY ([ID_COUNTRY], [ID_AZIENDA], [ID_CLIENTE], [ID_GARANZIA])
)
